apiVersion: 1

datasources:
  - name: VictoriaMetrics
    uid: victoriametrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      serviceMap:
        datasourceUid: victoriametrics
      tracesToLogsV2:
        datasourceUid: loki
        filterBySpanID: true
        filterByTraceID: true

  - name: InfluxDB Sensors
    uid: influxdb-sensors
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      defaultBucket: env_sensors
      organization: ahara
      version: Flux
    secureJsonData:
      token: ${INFLUXDB_ADMIN_TOKEN}

  - name: voltage-data
    uid: fewxrdtvmrk00a
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    jsonData:
      dbName: voltage-data
      httpMode: POST
      version: InfluxQL
    secureJsonData:
      password: ${INFLUXDB_ADMIN_TOKEN}

  - name: environment-data
    uid: aezaej38ebf9ce
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    user: admin
    jsonData:
      dbName: environment-data
      defaultBucket: environment-data
      httpMode: POST
      organization: ahara
      version: InfluxQL
    secureJsonData:
      password: ${INFLUXDB_ADMIN_TOKEN}

  - name: CloudWatch
    uid: cloudwatch
    type: CloudWatch
    access: proxy
    editable: true
    jsonData:
      authType: default
      defaultRegion: ${AWS_DEFAULT_REGION}
